name: Base Image Upstream Version

on:
  workflow_dispatch:

jobs:
  get-base-image-upstream-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Get Base Image Tag 
        id:   base-image
        run: |
          echo "name=${{ needs.params.outputs.base-img-name }}" >> "$GITHUB_OUTPUT"
          echo "tag=$( docker buildx imagetools inspect ${{ needs.params.outputs.base-img-name }}:${{ needs.params.outputs.base-img-tag}}  --format "{{json .Manifest}}"  | jq -r '.digest' )" >> "$GITHUB_OUTPUT"

     
