
name: Planner
on: 
  workflow_dispatch:
    inputs:
      force_rebuild:
        description:  'Force Rebuild'
        required:     false
        default:      false
        type:         boolean

  push:   
    branches: [ "master" ]
    paths:
      - '**/cmake-**.yml'
      - '**/cmake/**.json'

  schedule:
    - cron:  '0 0 * * 0' # “At 00:00 on every Sunday”

jobs:

  params:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        
      - name: Custom JSON reader Action
        id: inputs
        uses: Swapnil-Devops/recipe-reader-js@main
        with:
          json-file: ./recipe/cmake/recipe.json
          schema-file: ./.schema/recipe.json
        
      - name: outputs
        id: set_output
        run: |
               json_content=$(echo '${{ steps.inputs.outputs.json }}' | jq -c .)
               package_kind=$(echo "$json_content" | jq .package.kind)
              


               echo "package_kind=$package_kind" >> $GITHUB_OUTPUT
               echo "package_name=$package_name" >> $GITHUB_OUTPUT
          
               
               
      - name: Test outputs
        id:   test
        run: |
                  echo "${{ steps.set_output.outputs.package_kind }}"
                  echo "${{ steps.set_output.outputs.package_name }}"
                  
