name: Base Image Upstream Version

on:
  workflow_dispatch:

jobs:
  get-base-image-upstream-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Base Image Upstream Version
        id: get-base-image-version
        run: |
          baseImgName="${{ steps.inputs.outputs.base_img_name }}"
          baseImgTag="${{ steps.inputs.outputs.base_img_tag }}"
          manifest=$(docker buildx imagetools inspect "${baseImgName}:${baseImgTag}" --format "{{json .Manifest}}")
          upstreamVersion=$(echo "${manifest}" | jq -r '.config.Labels["org.opencontainers.image.version"]')

          echo "::set-output name=upstream_version::${upstreamVersion}"

      - name: Display Base Image Upstream Version
        run: |
          echo "Base Image Upstream Version: ${{ needs.get-base-image-version.outputs.upstream_version }}"
