name: Planner
on: 
  workflow_dispatch:
    inputs:
      force_rebuild:
        description:  'Force Rebuild'
        required:     false
        default:      false
        type:         boolean

  push:   
    branches: [ "master" ]
    paths:
      - '**/cmake-**.yml'
      - '**/cmake/**.json'

  schedule:
    - cron:  '0 0 * * 0' # “At 00:00 on every Sunday”

jobs:

  params:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Get Inputs
        id:   inputs
        run: |
               json_content=$(jq -c . < ./recipe/cmake/recipe.json)
               package_kind=$(echo "$json_content" | jq .package.kind)
               package_name=$(echo "$json_content" | jq .package.name)
               
      - name: Get Upstream Version
        id: upstream-version
        uses: your-action-repo/get-upstream-version-action@v3

#       - name: Display Upstream Version
#         run: echo "Upstream version is ${{ steps.upstream-version.outputs.version }}"    
               
      - name: Test Inputs
        id:   test
        run: |
                  echo "${{ steps.inputs.outputs.package_kind }}"
                  echo "${{ steps.inputs.outputs.package_name }}"
                 
