name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Available Builders
        id: get-builders
        run: |
          availableBuilders=$(docker buildx ls --output json | jq -r '.[].Name')
          echo "::set-output name=builders::${availableBuilders}"

      - name: Select Builder
        id: select-builder
        run: |
          availableBuilders="${{ steps.get-builders.outputs.builders }}"
          # Choose the appropriate builder based on your requirements
          # For example, if you want to use the default builder:
          builder=$(echo "${availableBuilders}" | grep default | head -n1)
          echo "::set-output name=builder::${builder}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ needs.select-builder.outputs.builder }}
          push: true
