name: Get Base Image Version
on:
  workflow_dispatch

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - name: Set Base Image
        run: echo "baseImgName=alpine:latest" >> $GITHUB_ENV
      
      - name: Get Base Image Version
        id: base-image
        run: |
          manifest=$(docker buildx imagetools inspect "${{ env.baseImgName }}" --format "{{json .Manifest}}")
          upstreamVersion=$(echo "${manifest}" | jq -r '.config.Labels["org.opencontainers.image.version"]')
          echo "::set-output name=upstreamVersion::${upstreamVersion}"
      
      - name: Display Version
        run: echo "Base Image Version: ${{ needs.base-image.outputs.upstreamVersion }}"
