name: Planner trail

on:
  workflow_dispatch:

jobs:
  get-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get Base Image Tag
        id: base-image
        run: |
          baseImgName="docker.io/debian:stable-slim"
          baseImgTag="latest"
    
          echo "name=${baseImgName}" >> $GITHUB_ENV
          manifest=$(docker buildx imagetools inspect "${baseImgName}:${baseImgTag}" --format "{{json .Manifest}}")
          tag=$(echo "${manifest}" | jq -r '.digest')
          echo "tag=${tag}" >> $GITHUB_ENV
