name: Planner trail

on:
  workflow_dispatch:

jobs:
  get-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set Base Image Name
        id: base-image
        run: |
          baseImgName="docker.io/debian:stable-slim"  # Replace with your base image name
          echo "IMAGE_NAME=${baseImgName}" >> $GITHUB_ENV
  
      - name: Get Base Image Digest
        id: base-image-digest
        run: |
          imageName="${{ needs.base-image.outputs.IMAGE_NAME }}"
          imageTag=""
          manifest=$(docker buildx imagetools inspect "${imageName}:${imageTag}" --format "{{json .Manifest}}")
          tag=$(echo "${manifest}" | jq -r '.digest')
          echo "IMAGE_DIGEST=${tag}" >> $GITHUB_ENV
