name: Planner trail

on:
  workflow_dispatch:

jobs:
  get-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set Base Image Name and Tag
        id: base-image
        run: |
          baseImgName="using docker.io/debian:stable-slim"  # Replace with your base image name
          baseImgTag="latest"          # Replace with your base image tag/version
          echo "::set-output name=image-name::${baseImgName}"
          echo "::set-output name=image-tag::${baseImgTag}"
  
      - name: Get Base Image Digest
        id: base-image-digest
        run: |
          imageName="${{ needs.base-image.outputs.image-name }}"
          imageTag="${{ needs.base-image.outputs.image-tag }}"
          manifest=$(docker buildx imagetools inspect "${imageName}:${imageTag}" --format "{{json .Manifest}}")
          tag=$(echo "${manifest}" | jq -r '.digest')
          echo "::set-output name=image-digest::${tag}"
