name: Test Node.js Rainfall

on: 
  workflow_dispatch:
    inputs:
      force_rebuild:
        description:  'Force Rebuild'
        required:     false
        default:      false
        type:         boolean

jobs:
  test:
    name: Run Tests from Nodejs-Rainfall
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Node.js Rainfall
        id: inputs
        uses: kiran-godse/ValidateRecipe@main
        with:
          json-file: ./recipe/cmake/recipe.json

 
