name: Test Node.js Rainfall

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests from Nodejs-Rainfall
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Node.js Rainfall
        uses: ./kiran-godse/Nodejs-Rainfall@main

      # Add more steps for the rest of the workflow in Quiz App
